LITERATURE_ANNOTATIONS = {
    1: {
        "broad_direction": "热障涂层、腐蚀与热机械可靠性",
        "medium_direction": "热障涂层服役与热-力-组织耦合",
        "abstract_summary": "该研究将 6-8% YSZ 基热障涂层用于 CRDI 发动机活塞，评估涂层对温度分布、热应力、显微缺陷、燃烧和排放的影响。",
        "study_object": "La2O3、TiO2、Al2O3、CeO2 改性的 YSZ 热障涂层活塞。",
        "methods": "有限元热-应力分析、显微组织观察和发动机性能/排放实验。",
        "core_result": "LYSZ 涂层表现出较少裂纹和脱层，并提高制动热效率、降低 HC/CO/烟度和未计热损失。",
        "fcva_connection": "与常温 FCVA 制备 YSZ 薄膜的直接工艺关联弱，但缺陷、脱层和热屏蔽结果可作为评价 FCVA 薄膜完整性与热功能的参照。",
        "complexity": "高：同时涉及多组分改性、涂层缺陷、热应力和发动机系统性能。",
        "review_sentence": "该文提示常温 FCVA-YSZ 薄膜若面向热防护应用，应重点控制裂纹、孔隙和界面脱层，而不仅关注相组成。",
    },
    2: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "水合、氢缺陷与质子迁移",
        "abstract_summary": "该文用第一性原理和从头算热力学研究立方 YSZ 的水合反应、氧空位、质子缺陷及化学膨胀。",
        "study_object": "含结构无序和氧空位的立方 YSZ 晶格。",
        "methods": "密度泛函理论、屏蔽交换泛函和温度/水蒸气分压相关的自由能计算。",
        "core_result": "计算给出了 YSZ 水合焓、熵、缺陷形成能和化学膨胀，并解释固相与气相贡献如何改变水合自由能。",
        "fcva_connection": "对常温 FCVA-YSZ 薄膜的关联在于氧空位和质子/水分相互作用会影响薄膜暴露空气或湿环境后的结构稳定性。",
        "complexity": "高：需要理解缺陷热力学、无序晶格和气固反应自由能。",
        "review_sentence": "该文可为讨论常温沉积 YSZ 薄膜中氧空位在湿环境下的演化提供原子尺度依据。",
    },
    3: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "水合、氢缺陷与质子迁移",
        "abstract_summary": "该研究面向氢燃料燃气轮机热障涂层，揭示四方 ZrO2/YSZ 中氢缺陷构型、形成能和迁移路径。",
        "study_object": "四方 ZrO2 和含 Y、氧空位的四方 YSZ。",
        "methods": "第一性原理计算缺陷构型、形成能、迁移路径和局域电子结构。",
        "core_result": "O-H 取向与 Zr-O 键长相关，氧空位对质子有显著俘获作用并导致质子迁移各向异性。",
        "fcva_connection": "常温 FCVA-YSZ 薄膜可能含较高缺陷密度，该文说明氧空位分布会影响氢/质子渗透与服役稳定性。",
        "complexity": "高：涉及晶相、缺陷复合体、迁移势垒和电子结构解释。",
        "review_sentence": "该文支持在 FCVA-YSZ 薄膜评价中加入氧空位调控与氢环境耐受性的讨论。",
    },
    4: {
        "broad_direction": "热障涂层、腐蚀与热机械可靠性",
        "medium_direction": "CMAS/熔盐腐蚀与裂纹失效",
        "abstract_summary": "该文结合实验和 DFT 研究 CMAS+NaVO3 熔体对 6-8 wt.% YSZ 热障涂层的渗透、相变和热化学腐蚀。",
        "study_object": "受 CMAS+NaVO3 混合熔体侵蚀的 YSZ 热障涂层和 YSZ 颗粒。",
        "methods": "涂层/熔体相互作用实验、陶瓷颗粒/熔体实验和 DFT 模拟。",
        "core_result": "CMAS+NaVO3 比单一 CMAS 渗透更强，0.5 h 内渗透深度超过 350 μm，并促进富 Y 立方 ZrO2 析出。",
        "fcva_connection": "与常温 FCVA 制膜的联系在于薄膜致密性、孔隙通道和晶相稳定性会决定其抗熔盐/CMAS 渗透能力。",
        "complexity": "中高：实验腐蚀现象较清楚，但机理解释依赖 DFT 和元素迁移分析。",
        "review_sentence": "该文可用于论证 FCVA-YSZ 薄膜需要通过低缺陷致密结构提升环境沉积物阻隔性能。",
    },
    5: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "相结构、电子结构与电解质性能",
        "abstract_summary": "该文研究立方 YSZ 固体电解质的晶体结构、微结构、电子结构及其与高温介电/电学性能的关系。",
        "study_object": "室温可稳定的立方 YSZ 固体电解质。",
        "methods": "XRD、SEM、电子结构计算和 GFourier 电子密度图分析。",
        "core_result": "文章强调立方 YSZ 中氧空位和电子/离子通道对电化学应用性能的关键作用。",
        "fcva_connection": "可为判断常温 FCVA 沉积薄膜是否形成目标立方相及是否具备离子传导通道提供结构参照。",
        "complexity": "中：以结构表征和电子结构关联为主，应用背景较宽。",
        "review_sentence": "该文适合放在 FCVA-YSZ 薄膜相结构与潜在电化学功能的背景综述中。",
    },
    6: {
        "broad_direction": "界面、电极与器件集成",
        "medium_direction": "Ni/YSZ 与 SOFC 电极界面",
        "abstract_summary": "该文用 DFT 建立 Ni/YSZ/气相三相界面模型，以理解固体氧化物电池中的表界面反应机制。",
        "study_object": "含不同氧空位、Y 排布、Y2O3 浓度和表面的 YSZ 以及 Ni/YSZ 界面。",
        "methods": "第一性原理筛选 YSZ 表面模型、Ni 接触结构和界面构型。",
        "core_result": "研究提出了更可靠的 YSZ 表面结构和兼顾计算成本的 Ni/YSZ 界面模型。",
        "fcva_connection": "与常温 FCVA-YSZ 薄膜的关联主要在表面和界面结构建模，可帮助解释薄膜与金属电极或基底接触时的缺陷构型。",
        "complexity": "高：模型变量多且集中在原子尺度界面构型选择。",
        "review_sentence": "该文可作为 FCVA-YSZ 薄膜后续电极集成或界面反应分析的理论模型参考。",
    },
    7: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "水合、氢缺陷与质子迁移",
        "abstract_summary": "该文结合第一性原理和 μSR 测量研究立方 YSZ 中质子缺陷的结合位置、迁移路径和短程扩散特征。",
        "study_object": "10.3 mol% 氧化钇含量、含氧空位补偿的立方 YSZ 准随机超胞。",
        "methods": "DFT、杂化泛函、质子迁移路径分析和 μSR 扩散活化能测量。",
        "core_result": "实验给出 0.17 eV 的扩散活化能，计算将质子转移和键重取向与 YSZ 局域无序结构联系起来。",
        "fcva_connection": "常温 FCVA-YSZ 薄膜若含非平衡缺陷和水/氢杂质，该文可解释质子在薄膜中的局域迁移和稳定性问题。",
        "complexity": "高：跨越量子计算、同位素实验和缺陷迁移机制。",
        "review_sentence": "该文强化了 FCVA-YSZ 薄膜研究中关注氢相关缺陷和环境吸附效应的必要性。",
    },
    8: {
        "broad_direction": "热障涂层、腐蚀与热机械可靠性",
        "medium_direction": "CMAS/熔盐腐蚀与裂纹失效",
        "abstract_summary": "该文用第一性原理研究堆垛层错对 YSZ 抗 CMAS 腐蚀能力的削弱以及 Nd 掺杂的改善作用。",
        "study_object": "含或不含 Nd 掺杂、带堆垛层错的 YSZ/CMAS 异质结。",
        "methods": "第一性原理计算界面稳定性、润湿角、离子穿透和扩散行为。",
        "core_result": "堆垛层错降低 YSZ 抗腐蚀性，而 Nd 掺杂通过增强结构稳定性和增大润湿角提升抗 CMAS 能力。",
        "fcva_connection": "常温 FCVA 薄膜可能存在非平衡缺陷，该文说明层错等结构缺陷会成为腐蚀薄弱点，掺杂可作为补偿策略。",
        "complexity": "高：需要同时理解缺陷、异质界面、润湿和多离子扩散。",
        "review_sentence": "该文可支撑 FCVA-YSZ 薄膜从“能沉积”进一步转向“低缺陷、抗腐蚀”结构设计。",
    },
    9: {
        "broad_direction": "界面、电极与器件集成",
        "medium_direction": "Ni/YSZ 与 SOFC 电极界面",
        "abstract_summary": "该文结合显微观察和 DFT 研究 CH4 环境中 Ni/YSZ 界面早期碳沉积的原子尺度机制。",
        "study_object": "甲烷气氛下的 Ni/YSZ 界面及不同氧空位构型。",
        "methods": "SEM、STEM 观察和 VASP 第一性原理计算 CH 片段吸附/成键势垒。",
        "core_result": "CH-CH 成键势垒约 0.6 eV，部分氧空位构型通过稳定 CH 吸附和增强 Ni-YSZ 黏附促进界面反应差异。",
        "fcva_connection": "金属/YSZ 界面缺陷会控制吸附反应和界面稳定性，尤其适用于 FCVA-YSZ 薄膜电极结构。",
        "complexity": "中高：界面反应路径明确，但依赖原子尺度吸附能和势垒解释。",
        "review_sentence": "该文可为 FCVA-YSZ 薄膜与金属层结合时的界面化学稳定性讨论提供案例。",
    },
    10: {
        "broad_direction": "表征、图像分析与应用拓展",
        "medium_direction": "光热与透明陶瓷应用",
        "abstract_summary": "该文针对透明纳米晶 YSZ 颅骨植入物，建立实验和计算模型评估激光照射下的光热安全性。",
        "study_object": "透明纳米晶 YSZ 陶瓷脑窗植入物。",
        "methods": "热成像实验、热-光耦合计算模型和参数反演。",
        "core_result": "激光照射下植入物底部温度未超过热损伤阈值，模型与实验差异约在 5% 内，吸收系数是关键参数。",
        "fcva_connection": "与常温 FCVA-YSZ 薄膜直接关联较弱，但热导率、吸收系数和透明性参数可为光学/热管理型 YSZ 薄膜提供参考。",
        "complexity": "中：重点是连续介质热-光模型和实验校准。",
        "review_sentence": "该文适合作为 YSZ 薄膜光热应用的旁证，而非 FCVA 制备机制的核心文献。",
    },
    11: {
        "broad_direction": "热障涂层、腐蚀与热机械可靠性",
        "medium_direction": "热障涂层服役与热-力-组织耦合",
        "abstract_summary": "该文研究 Yb2O3-Y2O3 共稳定 ZrO2 在 CMAS 熔体下的腐蚀行为、相稳定性和热物理性质。",
        "study_object": "YbYSZ 陶瓷及其与传统 YSZ 的对比体系。",
        "methods": "CMAS 腐蚀实验、热物性测试和第一性原理计算。",
        "core_result": "YbYSZ 相比 YSZ 具有更好 CMAS 抗性、更高热膨胀系数和更低热导率，原因与 Yb3+ 低扩散率和相稳定性有关。",
        "fcva_connection": "对常温 FCVA-YSZ 薄膜有材料设计启发，可考虑稀土共稳定以改善薄膜抗腐蚀和隔热性能。",
        "complexity": "中高：结合腐蚀、扩散、相稳定和热物性多维指标。",
        "review_sentence": "该文可用于说明 FCVA 制备 YSZ 薄膜时掺杂体系不仅影响相稳定，也可能决定 CMAS 耐受性。",
    },
    12: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "掺杂、电子结构与功能拓展",
        "abstract_summary": "该文用自旋极化 DFT 研究 Er3+ 掺杂 6.7 mol% Y2O3-YSZ 的电子和磁性质。",
        "study_object": "不同 Er2O3 掺杂浓度的 Er3+:YSZ 晶体模型。",
        "methods": "基于 PBE 和 PBE0 的自旋极化密度泛函计算。",
        "core_result": "Er3+:YSZ 被预测为稳定的反铁磁半导体，带隙约 5 eV，单个 Er3+ 对应 S=3/2。",
        "fcva_connection": "稀土掺杂可调控 FCVA-YSZ 薄膜电子结构和潜在功能性，但与热障或制备工艺关系间接。",
        "complexity": "中：主要集中在电子结构和磁性计算，应用场景较窄。",
        "review_sentence": "该文可作为 FCVA-YSZ 薄膜功能掺杂的扩展背景，但不宜作为常温制备与热障性能的主线依据。",
    },
    13: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "相变与相稳定热力学",
        "abstract_summary": "题录缺摘要，需阅读全文验证；题名显示该文关注 t*-YSZ 相变机制的第一性原理解释。",
        "study_object": "t*-YSZ 晶相及其相变过程。",
        "methods": "题名表明采用第一性原理计算，具体模型与参数需阅读全文验证。",
        "core_result": "题录缺摘要，无法确认其关于相变驱动力、稳定相或能垒的具体结论。",
        "fcva_connection": "可为常温 FCVA 制备 YSZ 薄膜后出现非平衡相或后续退火相变提供理论参照。",
        "complexity": "中高：涉及晶相稳定性和第一性原理能量分析，但摘要缺失增加判断不确定性。",
        "review_sentence": "该题录提示 t*-YSZ 相变可由第一性原理追踪，适合作为常温沉积非平衡 YSZ 薄膜相稳定问题的待验证理论文献。",
    },
    14: {
        "broad_direction": "界面、电极与器件集成",
        "medium_direction": "Ni/YSZ 与 SOFC 电极界面",
        "abstract_summary": "该文结合实验和 DFT 研究纯相及 Zr 掺杂 YMnO3+δ，说明 Zr 有助于稳定过量氧并可能降低氧离子迁移势垒。",
        "study_object": "与 YSZ 兼容的纯 YMnO3+δ 和 Zr 掺杂 Y1-xZrxMnO3+δ 阴极材料。",
        "methods": "采用中子衍射最大熵法、DFT 建模、电导与初步 EIS 测量相结合。",
        "core_result": "Zr 掺杂稳定层状锰氧化物中的间隙氧并诱导潜在混合离子-电子导电行为。",
        "fcva_connection": "与 FCVA 制备 YSZ 薄膜的直接工艺关联较弱，但可用于讨论 YSZ 薄膜在 SOFC 器件中与电极材料的界面兼容性。",
        "complexity": "高：跨结构表征、缺陷化学、DFT 和电化学性能。",
        "review_sentence": "该研究说明与 YSZ 接触的电极材料可通过 Zr 掺杂调节氧缺陷与迁移，对评估常温 FCVA-YSZ 薄膜的器件耦合环境有间接价值。",
    },
    15: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "表面、晶面与纳米结构活性",
        "abstract_summary": "该文用第一性原理比较 t-YSZ 低指数表面和微晶面，指出微晶面因更高表面能、费米能级和电荷重排而具有更强化学活性。",
        "study_object": "由低 Miller 指数晶面构成的 t-YSZ 纳米材料表面与微晶面界面。",
        "methods": "构建常规体表面模型和微晶面模型，计算表面能、几何结构、电子性质和 Mulliken 布居。",
        "core_result": "微晶面表面能远高于普通低指数表面，界面区域比单一晶面更易表现出高反应活性和 CMAS 腐蚀敏感性。",
        "fcva_connection": "高度相关，可解释常温 FCVA 薄膜中纳米晶、晶界和高能表面对后续稳定性与反应性的影响。",
        "complexity": "高：需要理解表面模型、电子结构和腐蚀反应之间的联系。",
        "review_sentence": "该文为常温 FCVA-YSZ 薄膜中高密度纳米晶界和非平衡表面可能带来的高化学活性提供了有力计算依据。",
    },
    16: {
        "broad_direction": "热障涂层、腐蚀与热机械可靠性",
        "medium_direction": "CMAS/熔盐腐蚀与裂纹失效",
        "abstract_summary": "该文用分子动力学研究 1523 K 下 CMAS 熔体在不同 YSZ 晶面上的润湿，发现 YSZ(110) 润湿最强且由表面氧分布驱动。",
        "study_object": "CMAS 熔体与 YSZ(110)、(001)、(111)、(101)、(010) 等表面。",
        "methods": "分子动力学计算接触角、黏度、表面张力、黏附功和分离功，并分析离子穿透行为。",
        "core_result": "YSZ 表面能和表面氧离子分布决定 CMAS 润湿趋势，其中 Mg、Si、O 尤其 Mg 离子对 YSZ(110) 表层穿透最明显。",
        "fcva_connection": "可用于讨论 FCVA-YSZ 薄膜晶面取向和表面氧结构对高温服役腐蚀抗性的影响。",
        "complexity": "高：涉及高温熔体、界面热力学和原子扩散机制。",
        "review_sentence": "该文表明 YSZ 晶面取向会显著改变 CMAS 润湿行为，可作为常温 FCVA 调控薄膜取向以提升耐腐蚀性的理论背景。",
    },
    17: {
        "broad_direction": "热障涂层、腐蚀与热机械可靠性",
        "medium_direction": "复合改性、致密化与力学响应",
        "abstract_summary": "题录缺摘要，需阅读全文验证；题名显示该文研究石墨烯掺杂 YSZ 的冲击压实，并结合实验与计算。",
        "study_object": "石墨烯掺杂的 YSZ 复合材料。",
        "methods": "题名表明包含冲击压实实验和计算模拟，具体计算尺度与表征方法需阅读全文验证。",
        "core_result": "题录缺摘要，无法确认石墨烯对 YSZ 致密化、力学性能或微结构演化的具体影响。",
        "fcva_connection": "与常温 FCVA-YSZ 薄膜直接关联较弱，但可间接参考复合掺杂和非平衡致密化对 YSZ 结构的影响。",
        "complexity": "中：主题涉及实验-计算耦合，但摘要缺失限制可用信息。",
        "review_sentence": "该题录可作为 YSZ 非传统致密化和复合改性研究的边缘参考，纳入 FCVA 综述前需阅读全文确认相关性。",
    },
    18: {
        "broad_direction": "界面、电极与器件集成",
        "medium_direction": "金属/氧化物黏附与异质界面",
        "abstract_summary": "题录缺摘要，需阅读全文验证；题名显示该文面向极端条件应用计算介孔二氧化硅和 YSZ 的界面性质。",
        "study_object": "介孔二氧化硅与 YSZ 相关材料界面。",
        "methods": "题名表明采用计算方法研究界面性质，具体是否为 DFT、分子动力学或连续模型需阅读全文验证。",
        "core_result": "题录缺摘要，无法确认其界面能、黏附、扩散或失效机制方面的结果。",
        "fcva_connection": "可能为 FCVA-YSZ 薄膜在复杂基底或极端环境中的界面稳定性提供间接背景。",
        "complexity": "中高：界面性质和极端条件应用通常涉及多尺度机制，但当前信息不足。",
        "review_sentence": "该题录提示 YSZ 界面计算可拓展到极端环境应用，但用于常温 FCVA 薄膜综述时需阅读全文筛选有效内容。",
    },
    19: {
        "broad_direction": "界面、电极与器件集成",
        "medium_direction": "金属/氧化物黏附与异质界面",
        "abstract_summary": "该文用 DFT 解释 Ag-CuO 钎料润湿 YSZ 的原因，并筛选可提升 Ag/YSZ 黏附的氧化物中间层。",
        "study_object": "Ag/YSZ、Ag/CuO、CuO/YSZ 及多种候选金属氧化物中间层界面。",
        "methods": "采用 DFT 计算界面黏附功和界面能，并建立描述符筛选单阳离子和多阳离子氧化物。",
        "core_result": "CuO 中间层比 Ag 中溶解氧团簇更显著提升 Ag 对 YSZ 的黏附，CuIO2、CuCaO2、Cu3TiO4 等被预测为潜在润湿促进层。",
        "fcva_connection": "可支持讨论 FCVA-YSZ 薄膜与金属电极、封接层或中间层之间的界面黏附设计。",
        "complexity": "高：包括界面建模、描述符构建和材料筛选。",
        "review_sentence": "该研究从界面黏附角度说明氧化物中间层可显著改善金属/YSZ 结合，对常温 FCVA-YSZ 薄膜后续集成封接有参考意义。",
    },
    20: {
        "broad_direction": "界面、电极与器件集成",
        "medium_direction": "金属/氧化物黏附与异质界面",
        "abstract_summary": "该文用第一性原理比较六方和立方 InN 在 YSZ(111) 上的界面，发现六方 InN 更稳定且有利于平整表面和较好导电性。",
        "study_object": "六方 InN(0001)/YSZ(111) 与立方 InN(111)/YSZ(111) 界面。",
        "methods": "采用第一性原理计算吸附能、扩散长度、有效质量和能带分散等界面电子性质。",
        "core_result": "六方 InN/YSZ 界面吸附稳定性更高，N 极性条件下较大扩散长度有利于原子迁移和平整生长。",
        "fcva_connection": "可用于理解 YSZ 薄膜作为异质外延或缓冲层时的界面结构与电学影响。",
        "complexity": "中高：涉及界面原子结构、外延相稳定和电子输运。",
        "review_sentence": "该文说明 YSZ(111) 界面可影响异质材料的相选择和导电特性，可作为 FCVA-YSZ 薄膜用于功能层集成时的界面理论参考。",
    },
    21: {
        "broad_direction": "热障涂层、腐蚀与热机械可靠性",
        "medium_direction": "CMAS/熔盐腐蚀与裂纹失效",
        "abstract_summary": "该文用 DFT 计算 CMAS、YSZ 涂层及反应产物界面的强度和残余应力，解释 CMAS 腐蚀后裂纹形核与扩展路径。",
        "study_object": "CMAS 腐蚀后的 YSZ 热障涂层、CaAl2Si2O8、MgAl2O4、Al2O3 和 MCrAlY 相关界面。",
        "methods": "采用密度泛函理论计算界面强度、原子键合和残余应力。",
        "core_result": "YSZ/CaAl2Si2O8 界面因 Zr-O 和 Ca-O 键弱而最易形核裂纹，低黏附强度和高残余应力促进裂纹沿若干界面扩展。",
        "fcva_connection": "可用于讨论 FCVA-YSZ 薄膜在高温污染环境中界面结合和应力失效的潜在风险。",
        "complexity": "高：将原子键合、界面强度和宏观裂纹路径联系起来。",
        "review_sentence": "该研究为 YSZ 薄膜服役时的界面弱键和残余应力失效提供计算证据，可补充常温 FCVA 制膜后的可靠性讨论。",
    },
    22: {
        "broad_direction": "热障涂层、腐蚀与热机械可靠性",
        "medium_direction": "CMAS/熔盐腐蚀与裂纹失效",
        "abstract_summary": "该文用第一性原理研究 CMAS 对 YSZ(111) 的高温腐蚀，指出 Ca/Y 和 Si/Y 扩散交换导致 Y 贫化、四方到单斜相变以及涂层开裂剥落。",
        "study_object": "CMAS/YSZ(111) 系统及受腐蚀的 YSZ 涂层。",
        "methods": "采用 DFT 计算体系能量，并结合高温下原子扩散行为分析腐蚀机制。",
        "core_result": "1513 K 以上 CMAS 中原子扩散更快，Ca、Si 与 Y 的交换形成夹层结构并诱发 YSZ 失稳相变。",
        "fcva_connection": "可为 FCVA-YSZ 薄膜中 Y 含量控制、晶相稳定性和高温污染耐受性提供警示。",
        "complexity": "高：涉及扩散、成分贫化、相变和热应力耦合。",
        "review_sentence": "该文表明 YSZ 的 Y 稳定剂流失会触发相变和剥落，对常温 FCVA-YSZ 薄膜的成分均匀性与后处理稳定性评价很重要。",
    },
    23: {
        "broad_direction": "表征、图像分析与应用拓展",
        "medium_direction": "微结构定量与形貌分析",
        "abstract_summary": "该文用计算图像分析评估 SPS-YSZ 涂层的孔隙率和表面粗糙度，并考察图像边界条件对孔隙率计算的影响。",
        "study_object": "悬浮等离子喷涂制备的 YSZ 涂层微结构和表面形貌。",
        "methods": "采用 ImageJ 进行孔隙率分析，并用 CLSM 与 SEM 形状恢复模式评估表面粗糙度。",
        "core_result": "孔隙率计算对圆度和尺寸阈值敏感，孔隙与粗糙度结果可关联到喷涂工艺变量和涂层应用场景。",
        "fcva_connection": "可借鉴其图像分析思路量化 FCVA-YSZ 薄膜的孔隙、颗粒和表面粗糙度。",
        "complexity": "中：方法偏图像处理和形貌统计，物理机理深度有限。",
        "review_sentence": "该文虽针对 SPS 涂层，但其孔隙率和粗糙度计算流程可迁移到常温 FCVA-YSZ 薄膜形貌评价中。",
    },
    24: {
        "broad_direction": "界面、电极与器件集成",
        "medium_direction": "Ni/YSZ 与 SOFC 电极界面",
        "abstract_summary": "题录缺摘要，需阅读全文验证；题名显示该文计算研究 YSZ 负载 Ni 的结构或性质。",
        "study_object": "负载在 YSZ 上的 Ni 物种或 Ni/YSZ 界面。",
        "methods": "题名仅说明为计算研究，具体模型、计算方法和评价指标需阅读全文验证。",
        "core_result": "题录缺摘要，无法确认 Ni 在 YSZ 上的黏附、电子转移、催化活性或稳定性结论。",
        "fcva_connection": "Ni/YSZ 是电化学器件典型界面，可作为 FCVA-YSZ 薄膜与金属功能层耦合的潜在参考。",
        "complexity": "中：界面计算可能重要，但题录信息不足。",
        "review_sentence": "该题录可能有助于理解 Ni 与 YSZ 的界面相互作用，是否服务于常温 FCVA-YSZ 薄膜集成仍需阅读全文确认。",
    },
    25: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "氧空位、离子扩散与缺陷构型",
        "abstract_summary": "该文用从头算解释立方 YSZ 中阳离子扩散远慢于氧离子扩散的原因。",
        "study_object": "立方 YSZ 中的阳离子空位、Schottky 缺陷和迁移路径。",
        "methods": "采用第一性原理计算分析缺陷形成和阳离子-空位交换迁移过程。",
        "core_result": "Schottky 对提供主要阳离子空位，阳离子迁移会强烈扰动邻近氧并产生高能垒。",
        "fcva_connection": "可用于说明常温 FCVA 沉积 YSZ 薄膜中 Y/Zr 阳离子重排困难，成分均匀性更依赖沉积能量和后处理。",
        "complexity": "高：计算建模要求高，但可直接作为缺陷迁移理论依据引用。",
        "review_sentence": "阳离子扩散计算表明 YSZ 的阳离子骨架在低温下较难重排，这为常温 FCVA 薄膜的非平衡结构理解提供依据。",
    },
    26: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "氧空位、离子扩散与缺陷构型",
        "abstract_summary": "该文讨论 YSZ 在复杂近玻璃态能量景观中寻找合理低能构型的问题。",
        "study_object": "含大量氧空位的 YSZ 固溶体构型、配位偏好和弛豫行为。",
        "methods": "结合经验势构型库、晶体化学筛选和第一性原理验证。",
        "core_result": "YSZ 存在长程配位偏好和局部受挫，快速弛豫由氧运动主导，慢弛豫需要协同阳离子扩散。",
        "fcva_connection": "常温 FCVA 薄膜可能冻结非平衡缺陷构型，该文可支撑后续退火促进相稳定和缺陷重排的讨论。",
        "complexity": "高：涉及构型搜索和从头算，但对解释低温沉积非平衡结构很有价值。",
        "review_sentence": "YSZ 构型计算显示其低能结构具有玻璃态特征，可用于解释常温 FCVA 制备薄膜中缺陷分布与后退火需求。",
    },
    27: {
        "broad_direction": "表征、图像分析与应用拓展",
        "medium_direction": "微结构定量与形貌分析",
        "abstract_summary": "该文比较 2D EBSD、3D EBSD 和体视学方法对不同烧结温度 YSZ 微结构的定量结果。",
        "study_object": "不同温度烧结 YSZ 陶瓷的晶粒尺寸分布和晶界密度。",
        "methods": "采用 2D/3D EBSD 表征并与体视学计算结果对比。",
        "core_result": "体视学平均截距长度比 EBSD 平均晶粒直径低约 20%，且体视学低估晶界密度。",
        "fcva_connection": "可为常温 FCVA-YSZ 薄膜退火后晶粒尺寸和晶界密度评价提供表征口径。",
        "complexity": "中高：3D EBSD 成本较高，薄膜样品还需考虑厚度和晶粒尺度限制。",
        "review_sentence": "YSZ 微结构定量研究提示，不同晶粒统计方法会带来系统差异，薄膜晶粒演化分析需统一表征标准。",
    },
    28: {
        "broad_direction": "界面、电极与器件集成",
        "medium_direction": "Ni/YSZ 与 SOFC 电极界面",
        "abstract_summary": "该文用三维电化学计算评估 SOFC 运行和氧化还原循环中 Ni-YSZ 阳极退化。",
        "study_object": "FIB-SEM 重构的 Ni-YSZ 阳极三维微结构及其电化学性能衰减。",
        "methods": "结合 FIB-SEM 三维重构、格子 Boltzmann 方法和实验过电位拟合。",
        "core_result": "三相界面密度变化不能充分解释退化，交换电流密度和 YSZ 离子电导变化更关键。",
        "fcva_connection": "对常温 FCVA-YSZ 薄膜的关联在于强调离子电导和微结构连通性应作为核心评价指标。",
        "complexity": "高：需要三维重构、电化学模型和实验拟合联用。",
        "review_sentence": "Ni-YSZ 阳极建模表明，YSZ 相的离子传输变化可能比几何三相界面更能控制器件性能。",
    },
    29: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "表面、晶面与纳米结构活性",
        "abstract_summary": "该文用周期 DFT 研究立方 ZrO2(111) 表面氧空位以及 8 mol% Y2O3 稳定 YSZ 表面的结构和电子性质。",
        "study_object": "清洁立方 ZrO2(111) 表面和 Y 掺杂 YSZ(111) 表面的氧空位构型。",
        "methods": "采用周期 DFT 比较氧空位位置、自旋态、Y 原子和空位排布构型。",
        "core_result": "Y2O3 掺杂稳定立方(111)表面，Y 倾向位于氧空位的次近邻位置且未引入带隙中态。",
        "fcva_connection": "与常温 FCVA 制备 YSZ 薄膜较相关，可指导沉积表面取向、氧空位控制和表面电子缺陷解释。",
        "complexity": "高：理论计算细致，但结论适合转化为薄膜表面缺陷调控依据。",
        "review_sentence": "YSZ(111) 表面 DFT 研究说明 Y 掺杂和氧空位排布会同时影响相稳定与电子结构，是薄膜缺陷调控的重要参考。",
    },
    30: {
        "broad_direction": "热障涂层、腐蚀与热机械可靠性",
        "medium_direction": "复合改性、致密化与力学响应",
        "abstract_summary": "该文基于三维重构微结构计算多孔 Ni-YSZ 复合材料的稳态蠕变响应。",
        "study_object": "SOFC 用多孔 Ni-YSZ 复合阳极及等效多孔 YSZ 骨架。",
        "methods": "采用三维微结构重构和数值均匀化计算稳态蠕变。",
        "core_result": "Ni 相承载应力很小，Ni-YSZ 蠕变可近似看作含额外孔隙的多孔 YSZ，孔隙使蠕变速率提高 8-10 倍。",
        "fcva_connection": "对常温 FCVA-YSZ 薄膜为间接参考，提示孔隙率和致密度会显著影响热机械稳定性。",
        "complexity": "高：依赖三维重构和本构参数，直接复现实验成本较高。",
        "review_sentence": "多孔 Ni-YSZ 蠕变计算强调孔隙对 YSZ 力学稳定性的放大作用，可作为 FCVA 薄膜致密化目标的旁证。",
    },
    31: {
        "broad_direction": "热障涂层、腐蚀与热机械可靠性",
        "medium_direction": "复合改性、致密化与力学响应",
        "abstract_summary": "该文提出由粉末衍射应变数据反演钇部分稳定氧化锆单晶弹性常数的方法。",
        "study_object": "四方钇部分稳定氧化锆的单晶弹性刚度矩阵。",
        "methods": "结合原位压缩中子衍射、有限元多晶模型和 Voigt/Reuss 平均反演。",
        "core_result": "获得一组与文献离散数据基本一致的优化弹性常数。",
        "fcva_connection": "可为常温 FCVA-YSZ 薄膜残余应力、附着力和相变力学建模提供材料参数。",
        "complexity": "高：实验平台要求高，但文献参数可直接服务薄膜应力分析。",
        "review_sentence": "YSZ 弹性常数反演研究为薄膜残余应力和热失配分析提供了可引用的力学基础数据。",
    },
    32: {
        "broad_direction": "热障涂层、腐蚀与热机械可靠性",
        "medium_direction": "复合改性、致密化与力学响应",
        "abstract_summary": "该文用第一性原理计算 Nb2O5 和 Ta2O5 掺杂对四方 YSZ 机械与热学性质的影响。",
        "study_object": "四方 YSZ、Nb 掺杂 YSZ 和 Ta 掺杂 YSZ 晶体结构。",
        "methods": "采用平面波 GGA 优化结构并由弹性常数推算模量、声速、Debye 温度和最低热导率。",
        "core_result": "Nb 和 Ta 掺杂均降低 YSZ 杨氏模量和最低热导率，其中 Ta2O5 效果更好。",
        "fcva_connection": "可为常温 FCVA 共沉积或复合靶制备低热导 YSZ 基薄膜提供掺杂选择依据。",
        "complexity": "中高：计算可复现性较好，但实验验证需要掺杂靶材或多源沉积控制。",
        "review_sentence": "Nb/Ta 掺杂计算表明高价氧化物可降低 YSZ 模量和热导，为 FCVA 制备改性 YSZ 薄膜提供设计线索。",
    },
    33: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "氧空位、离子扩散与缺陷构型",
        "abstract_summary": "该文开发用于 YSZ 的 Tangney-Scandolo 偶极势，并用第一性原理数据进行拟合验证。",
        "study_object": "YSZ 体相、晶界、相变和氧空位迁移行为。",
        "methods": "采用 DFT 生成能量、应力和力作为拟合数据，并进行分子动力学模拟。",
        "core_result": "所建势函数可再现相关 Y 含量下的立方-四方相变和氧空位迁移能垒。",
        "fcva_connection": "可用于模拟常温 FCVA-YSZ 薄膜后退火中的氧扩散、晶界传输和相演化。",
        "complexity": "高：势函数开发和 MD 门槛较高，但适合作为机理模拟工具来源。",
        "review_sentence": "YSZ 势函数与 MD 研究为跨尺度描述氧空位扩散和晶界输运提供了基础，可补充 FCVA 薄膜实验解释。",
    },
    34: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "氧空位、离子扩散与缺陷构型",
        "abstract_summary": "题录缺摘要，需阅读全文验证。",
        "study_object": "题名指向 YSZ 界面附近的缺陷分布与扩散行为，题录缺摘要，需阅读全文验证。",
        "methods": "题名仅显示为计算研究，具体采用 DFT、MD 或连续模型需阅读全文验证。",
        "core_result": "题录缺摘要，需阅读全文验证。",
        "fcva_connection": "可能关联常温 FCVA-YSZ 薄膜的膜/基底界面缺陷和氧空位扩散，但需阅读全文确认。",
        "complexity": "无法判断：题录缺摘要，需阅读全文验证。",
        "review_sentence": "该题录提示 YSZ 界面缺陷和扩散可能是薄膜界面稳定性的关键问题，但现有信息不足以直接引用结论。",
    },
    35: {
        "broad_direction": "界面、电极与器件集成",
        "medium_direction": "Ni/YSZ 与 SOFC 电极界面",
        "abstract_summary": "该文模拟 Ni-YSZ 阳极中镍颗粒渗流网络的电子电流分布。",
        "study_object": "Ni-YSZ 固体氧化物燃料电池金属陶瓷阳极。",
        "methods": "采用 Monte Carlo 渗流模型和松弛算法计算电流分布，并用镍丝实验测定失效电流密度。",
        "core_result": "镍体积分数和阳极孔隙率会显著改变局部电流密度分布。",
        "fcva_connection": "与常温 FCVA-YSZ 薄膜为间接关联，可提醒关注孔隙和连通缺陷造成的漏电或局部电流集中。",
        "complexity": "中高：模型实现可控，但实验部分涉及高温还原/氧化环境。",
        "review_sentence": "Ni-YSZ 阳极电流分布研究表明，微结构连通性会放大局部电输运差异，这对薄膜缺陷网络评价有启发。",
    },
    36: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "水合、氢缺陷与质子迁移",
        "abstract_summary": "该文用半局域和杂化泛函计算研究 10.3 mol% YSZ 中孤立氢的掺入和迁移。",
        "study_object": "立方 YSZ 中的氢杂质、氧空位和不同电荷态缺陷。",
        "methods": "采用第一性原理、杂化泛函和 NEB 最小能量路径计算。",
        "core_result": "氢表现为两性杂质，氧空位和晶格弛豫显著影响其稳定构型、深能级和迁移能垒。",
        "fcva_connection": "常温 FCVA-YSZ 薄膜若受残余气氛或后处理引入氢/水相关缺陷，该文可用于解释电导和缺陷态变化。",
        "complexity": "高：杂化泛函和 NEB 计算成本高，但机理结论对缺陷控制有参考价值。",
        "review_sentence": "氢缺陷计算说明氧空位会强烈调制 YSZ 中轻元素杂质的稳定性和迁移，对低温制备薄膜的环境敏感性分析有意义。",
    },
    37: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "基础模型与待全文确认",
        "abstract_summary": "题录缺摘要，需阅读全文验证。",
        "study_object": "研究对象为钇稳定氧化锆的计算模型，具体晶相、成分和缺陷对象需全文确认。",
        "methods": "题名显示采用计算建模方法，但具体是经验势、第一性原理还是热力学模型需阅读全文验证。",
        "core_result": "题录缺摘要，需阅读全文验证。",
        "fcva_connection": "可作为常温 FCVA 制备 YSZ 薄膜时讨论相稳定、缺陷结构和成分窗口的理论背景，但直接关联度需全文确认。",
        "complexity": "复杂度不确定，题录缺摘要，需阅读全文验证。",
        "review_sentence": "该题录提示其围绕 YSZ 计算建模展开，可为常温 FCVA-YSZ 薄膜的结构稳定性讨论提供背景，题录缺摘要，需阅读全文验证。",
    },
    38: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "氧空位、离子扩散与缺陷构型",
        "abstract_summary": "该文用原子间势模拟立方 YSZ 体相和表面，分析 Y 掺杂、氧空位、Y2O3 含量和表面取向对稳定性的影响。",
        "study_object": "钇稳定立方氧化锆的体相缺陷团簇及 (111)、(110) 等表面。",
        "methods": "采用 Mott-Littleton 稀释缺陷计算、超胞模型和表面能计算等原子间势模拟。",
        "core_result": "Y 掺杂倾向成对并位于氧空位次近邻位置，约 10 mol% Y2O3 附近出现两种稳定类立方相，且 (111) 表面占优并可能发生 Y 表面偏聚。",
        "fcva_connection": "它解释了低温非平衡沉积后 Y 分布、氧空位和择优表面对立方相稳定的贡献，对常温 FCVA-YSZ 薄膜很有用。",
        "complexity": "计算复杂度中等，实验转化需配合 XRD、XPS 或截面 TEM 验证成分、空位和表面取向。",
        "review_sentence": "体相-表面模拟表明，Y 含量、氧空位团簇和表面取向共同控制 c-YSZ 稳定性，可支撑常温 FCVA-YSZ 薄膜中低温成相与表面稳定机制的讨论。",
    },
    39: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "氧空位、离子扩散与缺陷构型",
        "abstract_summary": "该文用分子动力学模拟氮掺杂 YSZ 中氧、氮阴离子扩散，并与实验扩散率进行数量级比较。",
        "study_object": "组成近似 (Y0.2Zr0.8)-(O1.72N0.15) 的氮掺杂 YSZ 阴离子子晶格。",
        "methods": "采用 DL_POLY 分子动力学、Buckingham 型经验势，并为氮迁移构建相应势函数。",
        "core_result": "模拟扩散系数与实验同数量级，但氮扩散约比氧慢 5 倍，氧和氮迁移活化焓分别约为 1.2 和 1.4 eV。",
        "fcva_connection": "若常温 FCVA 采用含氮气氛或存在氮污染，该文可帮助判断氮进入 YSZ 后对阴离子迁移、氧空位补偿和后续退火行为的影响。",
        "complexity": "计算复杂度中等偏高，关键难点在可靠势函数和实验扩散数据校准。",
        "review_sentence": "氮掺杂 YSZ 扩散模拟说明异种阴离子会改变氧空位相关迁移过程，可作为常温 FCVA-YSZ 薄膜气氛杂质效应的参考。",
    },
    40: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "基础模型与待全文确认",
        "abstract_summary": "题录缺摘要，需阅读全文验证。",
        "study_object": "研究对象为立方 YSZ 中阳离子与阴离子的有序排列，具体成分和缺陷模型需全文确认。",
        "methods": "题名显示为计算研究，但具体计算框架、能量模型和采样方法需阅读全文验证。",
        "core_result": "题录缺摘要，需阅读全文验证。",
        "fcva_connection": "常温 FCVA 薄膜常处于非平衡或短程有序状态，该题录可能有助于比较沉积态薄膜与平衡有序结构的差异。",
        "complexity": "复杂度不确定，题录缺摘要，需阅读全文验证。",
        "review_sentence": "该题录指向 c-YSZ 中阳离子和阴离子有序问题，可为常温 FCVA 沉积态 YSZ 的局域结构解释提供线索，题录缺摘要，需阅读全文验证。",
    },
    41: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "掺杂、电子结构与功能拓展",
        "abstract_summary": "该文用第一性原理计算 YSZ 中不同顺磁缺陷中心的 EPR g 张量，以重新判定实验 T 中心的微观来源。",
        "study_object": "钇稳定立方氧化锆中的还原氧空位-Zr 复合体及 Ti 杂质相关顺磁中心。",
        "methods": "采用密度泛函微扰理论计算 EPR g 张量，并结合光学激发结果与实验 EPR/吸收谱对照。",
        "core_result": "计算排除了 Ti3+ 近邻单空位解释，并支持沿 <111> 的 Ti3+ 双空位复合体作为 T 中心来源。",
        "fcva_connection": "常温 FCVA 可能引入氧空位、还原 Zr 或靶材/腔体杂质，该文可为薄膜缺陷态、光吸收和 EPR 表征解释提供参照。",
        "complexity": "计算和表征复杂度较高，适合用于缺陷机理解释而非作为常规制备筛选方法。",
        "review_sentence": "第一性原理 EPR 研究表明 YSZ 中顺磁信号与氧空位-杂质复合体密切相关，可用于解释常温 FCVA-YSZ 薄膜中的还原缺陷信号。",
    },
    42: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "表面、晶面与纳米结构活性",
        "abstract_summary": "该文用第一性原理研究纯氧化锆和 Y 掺杂氧化锆表面终止，考察终止方式、金属支撑、膜厚及气氛对表面稳定性的影响。",
        "study_object": "四方氧化锆及 Y 掺杂氧化锆的极性/非极性表面，尤其是 (001) 与更稳定的 (101) 表面。",
        "methods": "采用第一性原理 slab 计算、不同表面终止模型、膜厚依赖分析和 H/O 气氛下表面相图。",
        "core_result": "Y 缺陷在 (001) 表面倾向远离表面，而在稳定的 (101) 表面靠近表面会进一步降低能量。",
        "fcva_connection": "该文直接有助于常温 FCVA-YSZ 薄膜的表面终止、厚度效应、氧气分压和 Y 表面偏聚讨论。",
        "complexity": "计算复杂度高，实验验证需表面敏感表征如 XPS、LEED、AFM 或截面 STEM。",
        "review_sentence": "表面计算显示 Y 掺杂与表面取向耦合决定氧化锆表面稳定性，可作为常温 FCVA-YSZ 薄膜表面结构与氧气氛控制的理论依据。",
    },
    43: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "相变与相稳定热力学",
        "abstract_summary": "该文热力学计算 ZrO2-CeO2-Y2O3 系中四方相与单斜相的 Gibbs 自由能差，并预测 Ms 转变温度。",
        "study_object": "CeO2-Y2O3 共掺 ZrO2，重点是四方-单斜相转变。",
        "methods": "基于相关二元体系热力学数据计算自由能差，并结合晶粒尺寸模型估算 T0 和 Ms。",
        "core_result": "对 8 mol% CeO2-0.5 mol% Y2O3-ZrO2，计算 T0 为 832.5 K、Ms 为 249.9 K，与 253 K 实验值接近。",
        "fcva_connection": "虽然不是典型 YSZ 组成，但可用于说明掺杂量、晶粒尺寸和相变温度对常温沉积氧化锆薄膜相稳定性的约束。",
        "complexity": "理论计算复杂度中等，实验验证需相组成和低温相变数据。",
        "review_sentence": "热力学结果强调共掺成分与晶粒尺寸会改变 ZrO2 相变温度，可为常温 FCVA-YSZ 薄膜避免单斜相转变提供比较依据。",
    },
    44: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "氧空位、离子扩散与缺陷构型",
        "abstract_summary": "该文结合 O-18 示踪扩散实验和分子动力学，研究不同 Y2O3 含量下 YSZ 的体相氧自扩散。",
        "study_object": "8-24 mol% Y2O3 稳定的 YSZ 体相氧扩散。",
        "methods": "采用 650-1200 K 气相 O-18 交换、SIMS 深度分析和 DL_POLY 分子动力学势函数比较。",
        "core_result": "氧扩散在约 10 mol% Y2O3 时最高，活化焓约 0.8-1.0 eV，MD 也再现实验的浓度依赖趋势。",
        "fcva_connection": "常温 FCVA 下氧扩散受限，该文可用于解释沉积态氧空位难以自发均匀化以及后处理氧化/退火的必要性。",
        "complexity": "实验复杂度较高，涉及同位素交换和 SIMS，计算部分也依赖势函数选择。",
        "review_sentence": "实验和 MD 证明 YSZ 氧扩散对 Y2O3 含量有峰值依赖，可支撑常温 FCVA-YSZ 薄膜中氧空位冻结与后处理调控的论述。",
    },
    45: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "相变与相稳定热力学",
        "abstract_summary": "该文评估 Y2O3-Yb2O3-ZrO2 体系相界和热力学数据，建立可描述伪三元相图的 CALPHAD 数据库。",
        "study_object": "Y2O3-ZrO2、Yb2O3-ZrO2、Y2O3-Yb2O3 及其 Y2O3-Yb2O3-ZrO2 伪三元体系。",
        "methods": "采用 CALPHAD 方法，将氧化物单元作为组元，并用规则/亚规则溶液模型拟合相平衡。",
        "core_result": "计算相图与实验相界吻合较好，形成了描述 Y/Yb 共稳定氧化锆的热力学数据库。",
        "fcva_connection": "可为常温 FCVA 使用复合靶或共掺稀土靶材时选择稳定立方/四方 YSZ 组成窗口提供相图依据。",
        "complexity": "建模复杂度中等，主要依赖热力学数据质量，实验侧需要成分-相结构校准。",
        "review_sentence": "CALPHAD 相图工作可扩展 YSZ 成分设计视角，为常温 FCVA 制备稀土共掺氧化锆薄膜提供热力学边界。",
    },
    46: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "掺杂、电子结构与功能拓展",
        "abstract_summary": "该文通过计算 X 射线吸收谱分析 ZrO2 掺杂 Y2O3 中 Zr 替代 Y 的可能位点选择性。",
        "study_object": "ZrO2 掺杂 Y2O3 中 Zr 阳离子的局域配位和替位位置。",
        "methods": "采用基于组态相互作用的阳离子 L2 边 XAS 计算，并显式考虑第一近邻环境、晶场分裂和跃迁项。",
        "core_result": "计算表明不同局域配位会造成可区分的吸收谱形，从而可预测 Zr 替代 Y 的位点选择性。",
        "fcva_connection": "该体系偏 Y2O3-rich，与常规 YSZ 不完全相同，但可帮助解释 FCVA 薄膜中 Y 富集区域或界面相的局域结构。",
        "complexity": "复杂度较高，需要谱学计算能力，并最好结合 XAS 实验验证。",
        "review_sentence": "XAS 计算表明局域配位可决定 Zr 在 Y2O3 基体中的占位选择，对分析常温 FCVA-YSZ 薄膜中非均匀掺杂或 Y 富集结构有参考价值。",
    },
    47: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "相变与相稳定热力学",
        "abstract_summary": "题录缺摘要，需阅读全文验证。",
        "study_object": "高压条件下 ZrO2-Y2O3 体系相平衡，具体压力范围和相区需全文确认。",
        "methods": "题名显示为相平衡计算，但热力学模型、输入数据和压力处理方式需阅读全文验证。",
        "core_result": "题录缺摘要，需阅读全文验证。",
        "fcva_connection": "高压相平衡本身与常温 FCVA 不直接等同，但可为讨论致密薄膜内应力或离子轰击诱导压力对相稳定性的影响提供边界。",
        "complexity": "复杂度不确定，题录缺摘要，需阅读全文验证。",
        "review_sentence": "高压 ZrO2-Y2O3 相平衡题录可能有助于讨论应力条件下 YSZ 相稳定性，但题录缺摘要，需阅读全文验证。",
    },
    48: {
        "broad_direction": "相稳定、缺陷与原子尺度模拟",
        "medium_direction": "相变与相稳定热力学",
        "abstract_summary": "题录缺摘要，需阅读全文验证。",
        "study_object": "ZrO2-Y2O3 体系相图，具体相区、温度范围和数据来源需全文确认。",
        "methods": "题名显示涉及相平衡热力学反问题求解和相图计算，具体算法需阅读全文验证。",
        "core_result": "题录缺摘要，需阅读全文验证。",
        "fcva_connection": "作为 ZrO2-Y2O3 基础相图研究，它可为常温 FCVA-YSZ 薄膜靶材成分和期望稳定相选择提供背景。",
        "complexity": "复杂度不确定，题录缺摘要，需阅读全文验证。",
        "review_sentence": "ZrO2-Y2O3 相图计算题录可作为 YSZ 成分-相稳定性背景文献，题录缺摘要，需阅读全文验证。",
    },
}
